// <auto-generated />
using System;
using Freshline.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Freshline.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreshlineDbContext))]
    partial class FreshlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Freshline.Core.Model.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAwaitingFirstInspection")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceRecordId");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Establishments_Latitude_Longitude");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Establishments_SourceId_ExternalId");

                    b.ToTable("Establishments", (string)null);
                });

            modelBuilder.Entity("Freshline.Core.Model.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("ClosedByAuthority")
                        .HasColumnType("bit");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("InspectedOn")
                        .HasColumnType("date");

                    b.Property<string>("InspectionType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("NormalisedSeverity")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("RawGrade")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("RawScore")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceRecordId");

                    b.HasIndex("EstablishmentId", "InspectedOn")
                        .HasDatabaseName("IX_Inspections_EstablishmentId_InspectedOn");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Inspections_SourceId_ExternalId");

                    b.ToTable("Inspections", (string)null);
                });

            modelBuilder.Entity("Freshline.Core.Model.SourceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_SourceRecords_SourceId_ExternalId");

                    b.ToTable("SourceRecords", (string)null);
                });

            modelBuilder.Entity("Freshline.Core.Model.SourceWatermark", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("HighWaterMark")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastRunCompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRunStartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SourceId");

                    b.ToTable("SourceWatermarks", (string)null);
                });

            modelBuilder.Entity("Freshline.Core.Model.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<long>("SourceRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.HasIndex("SourceRecordId");

                    b.HasIndex("SourceId", "Code")
                        .HasDatabaseName("IX_Violations_SourceId_Code");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Violations_SourceId_ExternalId");

                    b.ToTable("Violations", (string)null);
                });

            modelBuilder.Entity("Freshline.Core.Model.Establishment", b =>
                {
                    b.HasOne("Freshline.Core.Model.SourceRecord", "SourceRecord")
                        .WithMany()
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("Freshline.Core.Model.Inspection", b =>
                {
                    b.HasOne("Freshline.Core.Model.Establishment", "Establishment")
                        .WithMany("Inspections")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freshline.Core.Model.SourceRecord", "SourceRecord")
                        .WithMany()
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Establishment");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("Freshline.Core.Model.Violation", b =>
                {
                    b.HasOne("Freshline.Core.Model.Inspection", "Inspection")
                        .WithMany("Violations")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freshline.Core.Model.SourceRecord", "SourceRecord")
                        .WithMany()
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspection");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("Freshline.Core.Model.Establishment", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Freshline.Core.Model.Inspection", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
